### ISSUE TITLE
Some Clicker in JS?

### ISSUE THREAD

**Issue by Agrda215** [Agrda215/old-mdown#1]
# In This Clicker!
Inline Copy Three Codes i see:
```js
var score = 0;

document.getElementById("click").onclick = () => {
  score = score + 1
  document.getElementById("score").innerText = score
}
```
```html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Clicker</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
<h1 style="color:darkblue;" id="score">0</h1>
<button id="click">Click Out!</button>
<script src="script.js"></script>
</body>
</html>
```
```css
button#click {
  background-color:yellow;
}

p {
  text-align:center;
}
```
### You Do Spent!
- Are tips are clicker.
